Nop.Plugin.Payments.BrainTree/Controllers/BraintreeController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Plugin.Payments.Braintree.Models;
using Nop.Plugin.Payments.Braintree.Services;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Messages;
using Nop.Services.Security;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Models.Extensions;
using Nop.Web.Framework.Mvc;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Payments.Braintree.Controllers
{
    [Area(AreaNames.Admin)]
    [HttpsRequirement]
    [AutoValidateAntiforgeryToken]
    [ValidateIpAddress]
    [AuthorizeAdmin]
    [ValidateVendor]
    public class BraintreeController : BasePaymentController
    {
        #region Fields

        private readonly BraintreeMerchantService _braintreeMerchantService;
        private readonly ILocalizationService _localizationService;
        private readonly INotificationService _notificationService;
        private readonly IPermissionService _permissionService;
        private readonly ISettingService _settingService;
        private readonly IStoreContext _storeContext;

        #endregion

        #region Ctor

        public BraintreeController(BraintreeMerchantService braintreeMerchantService,
            ILocalizationService localizationService,
            INotificationService notificationService,
            IPermissionService permissionService,
            ISettingService settingService,
            IStoreContext storeContext)
        {
            _braintreeMerchantService = braintreeMerchantService;
            _localizationService = localizationService;
            _notificationService = notificationService;
            _permissionService = permissionService;
            _settingService = settingService;
            _storeContext = storeContext;
        }

        #endregion

        #region Methods

        public async Task<IActionResult> Configure()
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            //load settings for a chosen store scope
            var storeScope = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var braintreePaymentSettings = await _settingService.LoadSettingAsync<BraintreePaymentSettings>(storeScope);

            var model = new ConfigurationModel
            {
                ActiveStoreScopeConfiguration = storeScope,
                UseSandbox = braintreePaymentSettings.UseSandbox,
                PublicKey = braintreePaymentSettings.PublicKey,
                PrivateKey = braintreePaymentSettings.PrivateKey,
                MerchantId = braintreePaymentSettings.MerchantId,
                AdditionalFee = braintreePaymentSettings.AdditionalFee,
                AdditionalFeePercentage = braintreePaymentSettings.AdditionalFeePercentage,
                UseMultiCurrency = braintreePaymentSettings.UseMultiCurrency,
                Use3DS = braintreePaymentSettings.Use3DS
            };

            if (storeScope > 0)
            {
                model.UseSandbox_OverrideForStore = await _settingService.SettingExistsAsync(braintreePaymentSettings, settings => settings.UseSandbox, storeScope);
                model.PublicKey_OverrideForStore = await _settingService.SettingExistsAsync(braintreePaymentSettings, settings => settings.PublicKey, storeScope);
                model.PrivateKey_OverrideForStore = await _settingService.SettingExistsAsync(braintreePaymentSettings, settings => settings.PrivateKey, storeScope);
                model.MerchantId_OverrideForStore = await _settingService.SettingExistsAsync(braintreePaymentSettings, settings => settings.MerchantId, storeScope);
                model.AdditionalFee_OverrideForStore = await _settingService.SettingExistsAsync(braintreePaymentSettings, settings => settings.AdditionalFee, storeScope);
                model.AdditionalFeePercentage_OverrideForStore = await _settingService.SettingExistsAsync(braintreePaymentSettings, settings => settings.AdditionalFeePercentage, storeScope);
                model.UseMultiCurrency_OverrideForStore = await _settingService.SettingExistsAsync(braintreePaymentSettings, settings => settings.UseMultiCurrency, storeScope);
                model.Use3DS_OverrideForStore = await _settingService.SettingExistsAsync(braintreePaymentSettings, settings => settings.Use3DS, storeScope);
            }

            return View("~/Plugins/Payments.Braintree/Views/Configure.cshtml", model);
        }

        [HttpPost]
        public async Task<IActionResult> Configure(ConfigurationModel model)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            if (!ModelState.IsValid)
                return await Configure();

            //load settings for a chosen store scope
            var storeScope = await _storeContext.GetActiveStoreScopeConfigurationAsync();
            var braintreePaymentSettings = await _settingService.LoadSettingAsync<BraintreePaymentSettings>(storeScope);

            //save settings
            braintreePaymentSettings.UseSandbox = model.UseSandbox;
            braintreePaymentSettings.PublicKey = model.PublicKey;
            braintreePaymentSettings.PrivateKey = model.PrivateKey;
            braintreePaymentSettings.MerchantId = model.MerchantId;
            braintreePaymentSettings.AdditionalFee = model.AdditionalFee;
            braintreePaymentSettings.AdditionalFeePercentage = model.AdditionalFeePercentage;
            braintreePaymentSettings.UseMultiCurrency = model.UseMultiCurrency;
            braintreePaymentSettings.Use3DS = model.Use3DS;

            /* We do not clear cache after each setting update.
             * This behavior can increase performance because cached settings will not be cleared 
             * and loaded from database after each update */
            await _settingService.SaveSettingOverridablePerStoreAsync(braintreePaymentSettings, settings => settings.UseSandbox, model.UseSandbox_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(braintreePaymentSettings, settings => settings.PublicKey, model.PublicKey_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(braintreePaymentSettings, settings => settings.PrivateKey, model.PrivateKey_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(braintreePaymentSettings, settings => settings.MerchantId, model.MerchantId_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(braintreePaymentSettings, settings => settings.AdditionalFee, model.AdditionalFee_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(braintreePaymentSettings, settings => settings.AdditionalFeePercentage, model.AdditionalFeePercentage_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(braintreePaymentSettings, settings => settings.UseMultiCurrency, model.UseMultiCurrency_OverrideForStore, storeScope, false);
            await _settingService.SaveSettingOverridablePerStoreAsync(braintreePaymentSettings, settings => settings.Use3DS, model.Use3DS_OverrideForStore, storeScope, false);

            //now clear settings cache
            await _settingService.ClearCacheAsync();

            _notificationService.SuccessNotification(await _localizationService.GetResourceAsync("Admin.Plugins.Saved"));

            return await Configure();
        }

        [HttpPost]
        public virtual async Task<IActionResult> GetCurrencies(ConfigurationModel searchModel)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePaymentMethods))
                return await AccessDeniedDataTablesJson();

            //load settings for a chosen store scope
            var storeId = await _storeContext.GetActiveStoreScopeConfigurationAsync();

            //get merchant records
            var merchantRecords = _braintreeMerchantService.GetMerchants(storeId);

            //prepare model
            var model = new CurrencyListModel().PrepareToGrid(searchModel, merchantRecords, () =>
            {
                return merchantRecords.Select(currency => new CurrencyModel
                {
                    Id = currency.Id,
                    CurrencyCode = currency.CurrencyCode,
                    MerchantAccountId = currency.MerchantAccountId
                });
            });

            return Json(model);
        }

        [HttpPost]
        public virtual async Task<IActionResult> UpdateCurrency(CurrencyModel model)
        {
            if (!await _permissionService.AuthorizeAsync(StandardPermissionProvider.ManagePaymentMethods))
                return AccessDeniedView();

            await _braintreeMerchantService.UpdateMerchantAsync(model.Id, model.MerchantAccountId);

            return new NullJsonResult();
        }

        #endregion
    }
}

Nop.Plugin.Payments.BrainTree/Views/Configure.cshtml
@model ConfigurationModel

@{
    Layout = "_ConfigurePlugin";
}

@await Component.InvokeAsync("StoreScopeConfiguration")

<form asp-controller="Braintree" asp-action="Configure" method="post">
    <div class="cards-group">
        <div class="card card-default">
            <div class="card-body">
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="UseSandbox_OverrideForStore" asp-input="UseSandbox" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="UseSandbox" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="UseSandbox" />
                        <span asp-validation-for="UseSandbox"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="MerchantId_OverrideForStore" asp-input="MerchantId" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="MerchantId" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="MerchantId" asp-required="true" />
                        <span asp-validation-for="MerchantId"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="PrivateKey_OverrideForStore" asp-input="PrivateKey" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="PrivateKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="PrivateKey" asp-required="true" asp-value="@Model.PrivateKey" />
                        <span asp-validation-for="PrivateKey"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="PublicKey_OverrideForStore" asp-input="PublicKey" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="PublicKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="PublicKey" asp-required="true" />
                        <span asp-validation-for="PublicKey"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="AdditionalFee_OverrideForStore" asp-input="AdditionalFee" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="AdditionalFee" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="AdditionalFee" />
                        <span asp-validation-for="AdditionalFee"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="AdditionalFeePercentage_OverrideForStore" asp-input="AdditionalFeePercentage" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="AdditionalFeePercentage" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="AdditionalFeePercentage" />
                        <span asp-validation-for="AdditionalFeePercentage"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="Use3DS_OverrideForStore" asp-input="Use3DS" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="Use3DS" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Use3DS" />
                        <span asp-validation-for="Use3DS"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="UseMultiCurrency_OverrideForStore" asp-input="UseMultiCurrency" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="UseMultiCurrency" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="UseMultiCurrency" />
                        <span asp-validation-for="UseMultiCurrency"></span>
                    </div>
                </div>
                <div class="content" id="pnlUseMultiCurrency">
                    <div class="form-group row">
                        <div class="col-md-9 col-md-offset-3">
                            @await Html.PartialAsync("Table", new DataTablesModel
                            {
                                Name = "brain-tree-grid",
                                UrlRead = new DataUrl("GetCurrencies", "Braintree", null),
                                UrlUpdate = new DataUrl("UpdateCurrency", "Braintree", null),
                                SearchButtonId = "search-settings",
                                Length = Model.PageSize,
                                LengthMenu = Model.AvailablePageSizes,
                                ColumnCollection = new List<ColumnProperty>
                                {
                                    new ColumnProperty(nameof(CurrencyModel.CurrencyCode))
                                    {
                                        Title = T("Plugins.Payments.Braintree.Currency.Fields.CurrencyCode").Text,
                                        Width = "300",
                                        EditType = EditType.String
                                    },
                                    new ColumnProperty(nameof(CurrencyModel.MerchantAccountId))
                                    {
                                        Title = T("Plugins.Payments.Braintree.Currency.Fields.MerchantAccountId").Text,
                                        Width = "300",
                                        Editable = true,
                                        EditType = EditType.String
                                    },
                                    new ColumnProperty(nameof(CurrencyModel.Id))
                                    {
                                        Title = T("Admin.Common.Edit").Text,
                                        Width = "200",
                                        ClassName = NopColumnClassDefaults.Button,
                                        Render = new RenderButtonsInlineEdit()
                                    }
                                }
                            })
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-9 offset-3">
                        <input type="submit" name="save" class="btn bg-blue" value="@T("Admin.Common.Save")" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    $(document).ready(function () {
        $("#@Html.IdFor(model => model.UseMultiCurrency)").click(toggleUseMultiCurrency);
        toggleUseMultiCurrency();
    });

    function toggleUseMultiCurrency() {
        if ($('#@Html.IdFor(model => model.UseMultiCurrency)').is(':checked')) {
            $('#pnlUseMultiCurrency').showElement();
            updateTable($('#brain-tree-grid'));
        }
        else {
            $('#pnlUseMultiCurrency').hideElement();
        }
    }
</script>

Nop.Plugin.Payments.BrainTree/Views/PaymentInfo.3DS.cshtml
@model PaymentInfoModel

@{
    Layout = "";
    NopHtml.AddScriptParts(ResourceLocation.Footer, BraintreePaymentDefaults.ScriptPath, excludeFromBundle: true);
    NopHtml.AddScriptParts(ResourceLocation.Footer, BraintreePaymentDefaults.ClientScriptPath, excludeFromBundle: true);
    NopHtml.AddScriptParts(ResourceLocation.Footer, BraintreePaymentDefaults.HostedFieldsScriptPath, excludeFromBundle: true);
    NopHtml.AddScriptParts(ResourceLocation.Footer, BraintreePaymentDefaults.SecureScriptPath, excludeFromBundle: true);
}

<script asp-location="Footer">
    $(document).ready(function () {

        var authorization = '@Model.ClientToken';
        var submitForm = false;
        var stepBack = false;

        var onePageCheckout = @orderSettings.OnePageCheckoutEnabled.ToString().ToLower();

        var components = {
            client: null,
            threeDSecure: null,
            hostedFields: null
        };

        var bankFrame = document.querySelector('#braintree-authentication');

        $('.payment-info-next-step-button').attr('onclick', null);

        braintree.client.create({
            authorization: authorization
        }, onClientCreate);

        function onClientCreate(err, client) {
            if (err) {
                //console.log('client error:', err);
                return;
            }
            components.client = client;

            braintree.hostedFields.create({
                client: client,
                fields: {
                    number: {
                        selector: '#braintree-card-number',
                        placeholder: '•••• •••• •••• ••••'
                    },
                    cvv: {
                        selector: '#cc-cvv',
                        placeholder: 'CVV'
                    },
                    expirationDate: {
                        selector: '#braintree-expiration-date',
                        placeholder: 'MM/YY'
                    }
                }
            }, onComponent('hostedFields'));

            braintree.threeDSecure.create({
                client: client,
                version: 2
            }, onComponent('threeDSecure'));
        }

        function onComponent(name) {
            return function(err, component) {
                if (err)
                    return;

                components[name] = component;
            }
        }

        function addFrame(err, iframe) {
            bankFrame.appendChild(iframe);
        }

        function removeFrame() {
            var iframe = bankFrame.querySelector('iframe');
            iframe.parentNode.removeChild(iframe);
        }

        function verifyCard(payload) {

            @{
                var address = await addressService.GetAddressByIdAsync((await workContext.GetCurrentCustomerAsync()).BillingAddressId ?? 0);
                var stateProvince = await stateProvinceService.GetStateProvinceByAddressAsync(address);
                var country = await countryService.GetCountryByAddressAsync(address);
            }

            components.threeDSecure.verifyCard({
                bin : payload.details.bin,
                amount: '@((Model.OrderTotal ?? 0M).ToString("0.00", CultureInfo.InvariantCulture))',
                nonce: payload.nonce,
                addFrame: addFrame,
                removeFrame: removeFrame,
                challengeRequested: true,
                email: '@address?.Email',
                billingAddress: {
                    givenName: '@address?.FirstName',
                    surname: '@address?.LastName',
                    phoneNumber: '@address?.PhoneNumber',
                    streetAddress: '@address?.Address1',
                    extendedAddress: '@address?.Address2',
                    locality: '@address?.City',
                    region: '@stateProvince?.Abbreviation',
                    postalCode: '@address?.ZipPostalCode',
                    countryCodeAlpha2: '@country?.TwoLetterIsoCode'
                },
                onLookupComplete: function (data, next) {
                    // use `data` here, then call `next()`
                    next();
                }
            }, function (err, payload) {
                if (err) {
                    var currentErrorvalue = $('#@Html.IdFor(model => model.Errors)').val();
                    $('#@Html.IdFor(model => model.Errors)').val(currentErrorvalue + '|' + err.message);
                    return;
                }

                // Add the nonce to the form and submit
                if(payload.liabilityShiftPossible  && payload.liabilityShifted)
                {
                    document.querySelector('#CardNonce').value = payload.nonce;
                    submitForm = true;
                }
            });
        }

        $('.payment-info-next-step-button').on('click', function (data) {
            $('#braintree-errors').html('');
            if (!submitForm) {
                if (!stepBack) {
                    components.hostedFields.tokenize(function(err, payload) {
                        if (err) {
                            console.log('tokenization error:', err);

                            var currentErrorvalue = $('#@Html.IdFor(model => model.Errors)').val();
                            $('#@Html.IdFor(model => model.Errors)').val(currentErrorvalue + '|' + err.message);

                            $('#braintree-errors').html(err.message);
                            return;
                        }

                        verifyCard(payload);
                    });
                }
                return false;
            }
            else if (onePageCheckout) {
                submitForm = false;
                PaymentInfo.save();
            }
        });

        $(document).on('accordion_section_opened', function (data) {
            if (data && (data.currentSectionId == 'opc-billing' || data.currentSectionId == 'opc-shipping' || data.currentSectionId == 'opc-shipping_method' || data.currentSectionId == 'opc-payment_method')) {
                stepBack = true;
            }
        });
    });
</script>

<style type="text/css">
    .braintree-input {
        height: 36px;
        border: 1px solid #ddd;
        padding: 8px;
        vertical-align: middle;
        color: #777;
    }

    .invalid-feedback {
        display: none;
        width: 100%;
        margin-top: .25rem;
        font-size: 80%;
        color: #dc3545;
    }
</style>

<input type="hidden" asp-for="Errors" />
<div style="color:red; margin:0 auto" id="braintree-errors"></div>

<table width="100%" cellspacing="2" cellpadding="1" border="0">
    <tr>
        <td>
            <label>@T("Payment.CardNumber"):</label>
        </td>
        <td>
            <div class="braintree-input" id="braintree-card-number" style="width:165px;"></div>
        </td>
    </tr>
    <tr>
        <td>
            <label>@T("Payment.ExpirationDate"):</label>
        </td>
        <td>
            <div class="braintree-input" id="braintree-expiration-date" style="width:65px;"></div>
        </td>
    </tr>
    <tr>
        <td>
            <label>@T("Payment.CardCode"):</label>
        </td>
        <td>
            <div class="braintree-input" id="cc-cvv" style="width:65px;"></div>
            <input id="CardNonce" name="CardNonce" type="hidden" />
        </td>
    </tr>
</table>

<div id="braintree-authentication"></div>

@if (orderSettings.OnePageCheckoutEnabled)
{
    @NopHtml.GenerateInlineScripts(ResourceLocation.Footer)
}

Nop.Plugin.Payments.BrainTree/Views/PaymentInfo.cshtml
@model PaymentInfoModel

@{
    Layout = "";
}

<table width="100%" cellspacing="2" cellpadding="1" border="0">
    <tr>
        <td>
            @Html.LabelFor(model => model.CardholderName, false):
        </td>
        <td>
            @Html.TextBoxFor(model => model.CardholderName, new { style = "Width: 165px;", autocomplete = "off" })
            @Html.ValidationMessageFor(model => model.CardholderName)
        </td>
    </tr>
    <tr>
        <td>
            @Html.LabelFor(model => model.CardNumber, false):
        </td>
        <td>
            @Html.TextBoxFor(model => model.CardNumber, new { style = "Width: 165px;", autocomplete = "off", maxlength = 22 })
            @Html.ValidationMessageFor(model => model.CardNumber)
        </td>
    </tr>
    <tr>
        <td>
            @Html.LabelFor(model => model.ExpireMonth, false):
        </td>
        <td>
            @Html.DropDownListFor(model => model.ExpireMonth, Model.ExpireMonths)
            /
            @Html.DropDownListFor(model => model.ExpireYear, Model.ExpireYears)
        </td>
    </tr>
    <tr>
        <td>
            @Html.LabelFor(model => model.CardCode, false):
        </td>
        <td>
            @Html.TextBoxFor(model => model.CardCode, new { style = "Width: 60px;", autocomplete = "off", maxlength = 4 })
            @Html.ValidationMessageFor(model => model.CardCode)
        </td>
    </tr>
</table>